language: python
python: 3.8
addons:
  apt:
    packages:
    - enchant
before_install:
- travis_retry pip install --upgrade pip setuptools
install:
- travis_retry pip install --upgrade --editable .[dev]
cache: pip
script:
- make lint
- pytest -vvv --exitfirst tests/ --cov-fail-under 100 --cov src --cov tests
after_success:
- codecov
